export const lang = {
  en: {
    search: "Search",
    placeholder: "What would you like to watch today?",
    tvShow: "TV Shows",
    movies: "Movies",
    news: "News & Popular",
    myList: "My List",
    home: "Home",
    gptSearch: "GPT search",
    manageProfiles: "Manage Profiles",
    transferProfile: "Transfer Profile",
    account: "Account",
    helpCenter: "Help Centre",
    signout: "Sign out of Netflix",
    nowPlaying: "Now Playing",
    topRated: "Top Rated",
    upcoming: "Upcoming",
    popular: "Popular",
    play: "Play",
    moreInfo: "More Info",
  },
  hi: {
    search: "खोज",
    placeholder: "आज आप क्या देखना चाहेंगे?",
    tvShow: "टीवी शो",
    movies: "चलचित्र",
    news: "समाचार एवं लोकप्रिय",
    myList: "मेरी सूची",
    home: "होम",
    gptSearch: "जीपीटी खोज",
    manageProfiles: "प्रोफ़ाइल प्रबंधित करें",
    transferProfile: "प्रोफ़ाइल स्थानांतरण",
    account: "खाता",
    helpCenter: "सहायता केंद्र",
    signout: "नेटफ्लिक्स से साइन आउट करें",
    nowPlaying: "अब चल रही",
    topRated: "टॉप रेटेड",
    upcoming: "आगामी",
    popular: "लोकप्रिय",
    play: "शुरू",
    moreInfo: " और जानकारी",
  },
  sp: {
    search: "buscar",
    placeholder: " ¿Qué te gustaría ver hoy?",
    tvShow: "Programas de televisión",
    movies: "Películas",
    news: "Noticias y populares",
    myList: "Mi lista",
    home: "Hogar",
    gptSearch: "búsqueda GPT",
    manageProfiles: "Administrar perfiles",
    transferProfile: "Perfil de transferencia",
    account: "Cuenta",
    helpCenter: "Centro de ayuda",
    signout: "Cerrar sesión en Netflix",
    nowPlaying: " Ahora reproduciendo",
    topRated: "Los más valorados",
    upcoming: "Próximo",
    popular: "Popular",
    play: "Reproducir",
    moreInfo: "Más información",
  },
};
